[platformio]
src_dir = src
default_envs = cyd35

[env:cyd35]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
upload_speed = 921600
upload_port = COM7
monitor_port = COM7
board_build.partitions = min_spiffs.csv
lib_deps =
	bodmer/TFT_eSPI@^2.5.33
	bblanchon/ArduinoJson@^7
	https://github.com/Bodmer/U8g2_for_TFT_eSPI.git
	https://github.com/Bodmer/TJpg_Decoder.git
	https://github.com/Links2004/arduinoWebSockets.git
build_flags =
	-DUSER_SETUP_LOADED
	-DST7796_DRIVER
	-DTFT_WIDTH=320
	-DTFT_HEIGHT=480
	-DTFT_MISO=12
	-DTFT_MOSI=13
	-DTFT_SCLK=14
	-DTFT_CS=15
	-DTFT_DC=2
	-DTFT_RST=-1
	-DTFT_BL=27
	-DTFT_BACKLIGHT_ON=HIGH
	-DTOUCH_CS=33
	-DUSE_HSPI_PORT
	-DSPI_FREQUENCY=65000000
	-DSPI_READ_FREQUENCY=20000000
	-DSPI_TOUCH_FREQUENCY=2500000
	-DLOAD_GLCD
	-DLOAD_FONT2
	-DLOAD_FONT4
	-DLOAD_FONT6
	-DLOAD_FONT7
	-DLOAD_FONT8
	-DLOAD_GFXFF
	-DSMOOTH_FONT
